# Generated by Django 4.2 on 2023-04-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('company', models.TextField()),
                ('contactName', models.TextField()),
                ('projectName', models.TextField()),
                ('description', models.TextField()),
                ('goals', models.TextField()),
                ('price', models.IntegerField()),
                ('projectLength', models.IntegerField()),
                ('criteria', models.TextField()),
                ('timeframe', models.TextField()),
                ('target', models.TextField()),
                ('technologies', models.TextField()),
                ('mockup', models.TextField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
